# Module 1 - OLTP Database

This notebook summarizes the tasks performed during Module 1 of the IBM Data Engineering Capstone Project for SoftCart.com, an e-commerce company. The module focused on designing and managing an Online Transaction Processing (OLTP) database using MySQL to handle transactional data. The original lab was conducted in a cloud-based Skills Network Labs environment with MySQL 8.0.22 and phpMyAdmin 5.0.4 running in a Docker container. This report replicates the tasks offline using a local MySQL server and phpMyAdmin to ensure accessibility for a GitHub portfolio. Each task is presented in a separate cell with process descriptions, representative solutions (SQL commands, Bash scripts, or instructions), placeholders for outputs, dataset schemas, and screenshot placeholders for manual insertion. The notebook is designed to be recruiter-friendly, showcasing data engineering skills in database design and administration.

## Objectives

- Verify the MySQL server environment.
- Design and create a `sales` database and `sales_data` table.
- Load data from `oltpdata.csv` into the `sales_data` table and verify the import.
- Perform administrative tasks, including creating an index and exporting data with a Bash script.

## Tools / Software

- **MySQL**: Open-source relational database (version 8.0 or later, replacing cloud-based MySQL 8.0.22).
- **phpMyAdmin**: Web-based database management tool (replacing cloud-based phpMyAdmin 5.0.4).
- **Bash**: For scripting data export tasks.
- **Jupyter Notebook**: For documentation and task presentation.

## Notes

- The original lab used a cloud IDE with MySQL and phpMyAdmin in Docker. This notebook uses a local MySQL server and phpMyAdmin (via Docker or direct installation) for offline replication.
- Screenshots use provided names (e.g., `createtable.jpg`, `importdata.jpg`) with placeholders (e.g., `[path/to/createtable.jpg]`) for manual insertion.
- The `oltpdata.csv` schema is assumed; a placeholder section allows edits.
- Outputs are generic examples; replace with actual results.
- The `oltpdata.csv` file is assumed to be in the repository (`datasets/oltpdata.csv`); update paths as needed.

## Dataset Schema (Adjustable)

**Placeholder for oltpdata.csv Schema**:
- **Description**: The `oltpdata.csv` contains transactional sales data for the `sales_data` table.
- **Columns** (assumed based on instructions):
  - `order_id` (INT): Unique identifier for each order.
  - `product_id` (INT): Identifier for the product sold.
  - `customer_id` (INT): Identifier for the customer.
  - `timestamp` (DATETIME): Date and time of the transaction.
  - `amount` (DECIMAL): Transaction amount.
- **File Location**: `datasets/oltpdata.csv` (to be added to the repository).
- **Notes**: Edit this section to specify the actual column names and data types from `oltpdata.csv`. Adjust SQL commands below if the schema differs.

## Exercise 1: Check the Lab Environment

**Objective**: Start and verify the MySQL server.

**Process Description**:
- Started the MySQL server locally to replicate the cloud-based environment.
- Verified the server status using a command-line check.

**Solution**:
```bash
# Start MySQL server
sudo service mysql start
# Verify status
mysqladmin -u root -p status
```

**Your Output**:
```text
-- Add output from the mysqladmin status command.
-- Example:
Uptime: 3600  Threads: 1  Questions: 10  Slow queries: 0  Opens: 100  Flush tables: 1  Open tables: 20
```

**Expected Output**:
- Confirmation that the MySQL server is running (e.g., uptime, threads).

**Screenshot Placeholder**:
- Screenshot of the MySQL status command and output: `[path/to/mysql_status.jpg]`.

**Note**: Ensure MySQL is installed locally or via Docker. Insert screenshot path manually.

## Exercise 2, Task 1: Create a Database

**Objective**: Create a database named `sales`.

**Process Description**:
- Connected to the MySQL server using the root user.
- Created the `sales` database using a SQL command.
- Verified the database creation by listing databases.

**Solution**:
```sql
-- Connect to MySQL
mysql -u root -p
-- Create database
CREATE DATABASE sales;
-- Verify creation
SHOW DATABASES;
```

**Your Output**:
```text
-- Add output from the CREATE DATABASE and SHOW DATABASES commands.
-- Example:
Query OK, 1 row affected (0.00 sec)
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| sales              |
+--------------------+
3 rows in set (0.00 sec)
```

**Expected Output**:
- `CREATE DATABASE`: Confirmation of database creation.
- `SHOW DATABASES`: List including `sales`.

**Screenshot Placeholder**:
- Screenshot of the database creation and verification output: `[path/to/createdatabase.jpg]`.

**Note**: Update credentials if needed. Insert screenshot path manually.

## Exercise 2, Task 2: Design the Table `sales_data`

**Objective**: Design and create the `sales_data` table in the `sales` database based on sample data.

**Process Description**:
- Designed the `sales_data` table to match the assumed schema of `oltpdata.csv`.
- Created the table using a SQL command in the `sales` database.
- Saved the SQL statement in a text file.

**Solution**:
```sql
-- Connect to sales database
USE sales;
-- Create sales_data table
CREATE TABLE sales_data (
    order_id INT PRIMARY KEY,
    product_id INT,
    customer_id INT,
    timestamp DATETIME,
    amount DECIMAL(10,2)
);
-- Save to file
-- echo "CREATE TABLE sales_data ..." > create_sales_data.sql
```

**Your Output**:
```text
-- Add output from the CREATE TABLE command.
-- Example:
Query OK, 0 rows affected (0.01 sec)
```

**Expected Output**:
- Confirmation of table creation.

**Screenshot Placeholder**:
- Screenshot of the `CREATE TABLE` command and output: `[path/to/createtable.jpg]`.

**Note**: Adjust the table schema based on the actual `oltpdata.csv` structure. Save the SQL statement in `module_1/queries/create_sales_data.sql`. Insert screenshot path manually.

## Exercise 3, Task 3: Import Data from `oltpdata.csv`

**Objective**: Import `oltpdata.csv` into the `sales_data` table using phpMyAdmin.

**Process Description**:
- Accessed phpMyAdmin locally (e.g., http://localhost/phpmyadmin).
- Selected the `sales` database and `sales_data` table.
- Used the phpMyAdmin import feature to upload `oltpdata.csv` with CSV settings (e.g., comma delimiter, header row).
- Verified the import status.

**Solution**:
```text
# Start phpMyAdmin (example using Docker)
docker run -d -p 8080:80 phpmyadmin/phpmyadmin
# Steps in phpMyAdmin UI:
# 1. Log in to phpMyAdmin (http://localhost:8080)
# 2. Select 'sales' database
# 3. Select 'sales_data' table
# 4. Go to 'Import' tab
# 5. Choose file: datasets/oltpdata.csv
# 6. Set format: CSV, delimiter: ',', check 'First row is column names'
# 7. Click 'Go'
```

**Your Output**:
```text
-- Add output from phpMyAdmin import status.
-- Example:
Import has been successfully finished, 1000 rows imported.
```

**Expected Output**:
- Confirmation of rows imported (e.g., number of rows).

**Screenshot Placeholder**:
- Screenshot of phpMyAdmin import status: `[path/to/importdata.jpg]`.

**Note**: Ensure `oltpdata.csv` is in `module_1/datasets/`. Adjust phpMyAdmin settings based on the actual schema. Insert screenshot path manually.

## Exercise 3, Task 4: List Tables in `sales` Database

**Objective**: List all tables in the `sales` database to verify the presence of `sales_data`.

**Process Description**:
- Connected to the `sales` database in MySQL.
- Executed the `SHOW TABLES` command.
- Saved the SQL statement in a text file.

**Solution**:
```sql
-- Connect to sales database
USE sales;
-- List tables
SHOW TABLES;
-- Save to file
-- echo "SHOW TABLES;" > list_tables.sql
```

**Your Output**:
```text
-- Add output from the SHOW TABLES command.
-- Example:
+-----------------+
| Tables_in_sales |
+-----------------+
| sales_data      |
+-----------------+
1 row in set (0.00 sec)
```

**Expected Output**:
- List of tables, including `sales_data`.

**Screenshot Placeholder**:
- Screenshot of the `SHOW TABLES` command and output: `[path/to/listtables.jpg]`.

**Note**: Save the SQL statement in `module_1/queries/list_tables.sql`. Insert screenshot path manually.

## Exercise 3, Task 5: Count Records in `sales_data`

**Objective**: Count the number of records in the `sales_data` table.

**Process Description**:
- Connected to the `sales` database.
- Executed a `SELECT COUNT(*)` query on `sales_data`.
- Saved the SQL statement in a text file.

**Solution**:
```sql
-- Connect to sales database
USE sales;
-- Count records
SELECT COUNT(*) AS record_count FROM sales_data;
-- Save to file
-- echo "SELECT COUNT(*) AS record_count FROM sales_data;" > count_records.sql
```

**Your Output**:
```text
-- Add output from the COUNT query.
-- Example:
+--------------+
| record_count |
+--------------+
| 1000         |
+--------------+
1 row in set (0.00 sec)
```

**Expected Output**:
- Number of records in `sales_data` (e.g., 1000).

**Screenshot Placeholder**:
- Screenshot of the `COUNT` query and output: `[path/to/salesrows.jpg]`.

**Note**: Save the SQL statement in `module_1/queries/count_records.sql`. Insert screenshot path manually.

## Exercise 4, Task 6: Create an Index

**Objective**: Create an index named `ts` on the `timestamp` field of `sales_data`.

**Process Description**:
- Connected to the `sales` database.
- Created an index using the `CREATE INDEX` command.

**Solution**:
```sql
-- Connect to sales database
USE sales;
-- Create index
CREATE INDEX ts ON sales_data(timestamp);
```

**Your Output**:
```text
-- Add output from the CREATE INDEX command.
-- Example:
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

**Expected Output**:
- Confirmation of index creation.

**Screenshot Placeholder**:
- Screenshot of the `CREATE INDEX` command and output: `[path/to/createindex.jpg]`.

**Note**: Ensure the `timestamp` column exists in `sales_data`. Insert screenshot path manually.

## Exercise 4, Task 7: List Indexes

**Objective**: List all indexes on the `sales_data` table.

**Process Description**:
- Connected to the `sales` database.
- Executed the `SHOW INDEXES` command to list indexes.
- Saved the SQL statement in a text file.

**Solution**:
```sql
-- Connect to sales database
USE sales;
-- List indexes
SHOW INDEXES FROM sales_data;
-- Save to file
-- echo "SHOW INDEXES FROM sales_data;" > list_indexes.sql
```

**Your Output**:
```text
-- Add output from the SHOW INDEXES command.
-- Example:
+------------+------------+----------+--------------+-------------+-----------+
| Table      | Non_unique | Key_name | Seq_in_index | Column_name | Collation |
+------------+------------+----------+--------------+-------------+-----------+
| sales_data | 0          | PRIMARY  | 1            | order_id    | A         |
| sales_data | 1          | ts       | 1            | timestamp   | A         |
+------------+------------+----------+--------------+-------------+-----------+
2 rows in set (0.00 sec)
```

**Expected Output**:
- List of indexes, including `PRIMARY` (on `order_id`) and `ts` (on `timestamp`).

**Screenshot Placeholder**:
- Screenshot of the `SHOW INDEXES` command and output: `[path/to/listindexes.jpg]`.

**Note**: Save the SQL statement in `module_1/queries/list_indexes.sql`. Insert screenshot path manually.

## Exercise 4, Task 8: Export Data with Bash Script

**Objective**: Write a Bash script (`datadump.sh`) to export all rows from `sales_data` to `sales_data.sql`.

**Process Description**:
- Created a Bash script to export the `sales_data` table using `mysqldump`.
- Executed the script and verified the output file.
- Saved the script in a text file.

**Solution**:
```bash
# datadump.sh
#!/bin/bash
mysqldump -u root -p --no-create-info sales sales_data > sales_data.sql
# Make script executable
chmod +x datadump.sh
# Run script
./datadump.sh
# Verify output
ls -l sales_data.sql
```

**Your Output**:
```text
-- Add output from the script execution and ls command.
-- Example:
-- Enter password: [hidden]
-rw-r--r-- 1 user user 123456 Jul 16 20:00 sales_data.sql
```

**Expected Output**:
- Confirmation of export (prompt for password in `mysqldump`).
- File details for `sales_data.sql`.

**Screenshot Placeholder**:
- Screenshot of the script and execution output: `[path/to/exportdata.jpg]`.

**Note**: Save the script as `module_1/datadump.sh`. Update credentials and paths as needed. Insert screenshot path manually.

## Analysis and Conclusions

- **Summary**: Module 1 tasks were replicated offline using MySQL for database operations, phpMyAdmin for data import, and Bash for data export. The `sales` database and `sales_data` table were created, data was imported from `oltpdata.csv`, and administrative tasks (indexing, exporting) were completed, mirroring the cloud-based lab.
- **Offline Replication**:
  - Local MySQL replaced the cloud-based MySQL 8.0.22, supporting identical SQL commands.
  - phpMyAdmin (via Docker or local install) replicated the cloud IDE’s import functionality.
  - Bash scripting with `mysqldump` provided a portable export solution.
- **Challenges**:
  - Setting up MySQL and phpMyAdmin locally requires proper configuration (e.g., credentials, ports).
  - The `oltpdata.csv` schema is assumed; incorrect columns may require SQL adjustments.
  - Docker setup for phpMyAdmin may need port or permission troubleshooting.
- **Portfolio Notes**: This notebook is designed for a GitHub portfolio, with clear task descriptions, representative solutions, and placeholders for outputs and screenshots to ensure recruiter-friendly documentation.

## Additional Notes

- **Dataset Access**: Place `oltpdata.csv` in `module_1/datasets/`. Update paths in import commands if renamed.
- **Screenshots**: Insert paths and names for screenshots manually (e.g., `createtable.jpg`, `importdata.jpg`). Ensure they match the described purpose.
- **Outputs**: Replace generic outputs with actual results from your executions.
- **Setup Instructions**: Install MySQL (`sudo apt install mysql-server`), phpMyAdmin (`docker run -d -p 8080:80 phpmyadmin/phpmyadmin`), and ensure Bash is available. See the repository README for detailed steps.
- **Adjustments**: Edit the schema placeholder and SQL commands once the `oltpdata.csv` structure is confirmed. Save SQL files in `module_1/queries/` and `datadump.sh` in `module_1/`.